extern u64 gWaterPipeWaterfallDL_Effect_WaterFall03_ia8[];
extern Vtx gWaterPipeWaterfallDL_gWaterPipeWaterfallDL_mesh_layer_Transparent_vtx_cull[8];
extern Vtx gWaterPipeWaterfallDL_gWaterPipeWaterfallDL_mesh_layer_Transparent_vtx_0[8];
extern Gfx gWaterPipeWaterfallDL_gWaterPipeWaterfallDL_mesh_layer_Transparent_tri_0[];
extern Gfx mat_gWaterPipeWaterfallDL_f3dlite_material_344_layerTransparent[];
extern Gfx gWaterPipeWaterfallDL[];
