#ifndef ICON_ITEM_STATIC_H
#define ICON_ITEM_STATIC_H 1

extern u64 gNewPausePromptCursorTex[];
extern u64 gNewPauseCursorTopLeftTex[];
extern u64 gNewPauseCursorTopRightTex[];
extern u64 gNewPauseCursorBottomLeftTex[];
extern u64 gNewPauseCursorBottomRightTex[];
extern u64 gNewPauseBg00[];
extern u64 gNewPauseBg01[];
extern u64 gNewPauseBg02[];
extern u64 gNewPauseBg10[];
extern u64 gNewPauseBg12[];
extern u64 gNewPauseBg20[];
extern u64 gNewPauseBg22[];
extern u64 gNewPauseBg30[];
extern u64 gNewPauseBg32[];
extern u64 gNewPauseBg40[];
extern u64 gNewPauseBg41[];
extern u64 gNewPauseBg42[];
extern u64 gNewPauseBgEmpty[];
extern u64 gNewPauseEquipmentHeader[];
extern u64 gNewPauseItemsHeader[];
extern u64 gNewPauseItemBg[];
extern u64 gNewPauseSavePrompt[];
extern u64 gNewPauseYesTex[];
extern u64 gNewPauseNoTex[];
extern u64 gNewPauseItemNameBgTex[];
extern u64 gBluePotionNameTex[];
extern u64 gBombsNameTex[];
extern u64 gBoosterGauntletsNameTex[];
extern u64 gEmptyBottleNameTex[];
extern u64 gFairyNameTex[];
extern u64 gGreenPotionNameTex[];
extern u64 gHeatsinkBuckleNameTex[];
extern u64 gHookshotNameTex[];
extern u64 gMirrorShieldNameTex[];
extern u64 gRedPotionNameTex[];
extern u64 gZoraAmuletNameTex[];
extern u64 gWaterNameTex[];
extern u64 gPauseMenuBgGameOver[];
extern u64 gPauseContinuePrompt[];
#endif
