extern u64 gReactorCircuitCenterBeamDL_Reactor_Beam_00_i8[];
extern Vtx gReactorCircuitCenterBeamDL_gReactorCircuitCenterBeamDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gReactorCircuitCenterBeamDL_gReactorCircuitCenterBeamDL_mesh_layer_Opaque_vtx_0[14];
extern Gfx gReactorCircuitCenterBeamDL_gReactorCircuitCenterBeamDL_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gReactorCircuitCenterBeamDL_f3dlite_material_056_layerOpaque[];
extern Gfx gReactorCircuitCenterBeamDL[];
