extern u64 gReactorCircuitLowerBeamDL_Reactor_Beam_00_i8[];
extern Vtx gReactorCircuitLowerBeamDL_gReactorCircuitLowerBeamDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gReactorCircuitLowerBeamDL_gReactorCircuitLowerBeamDL_mesh_layer_Opaque_vtx_0[11];
extern Gfx gReactorCircuitLowerBeamDL_gReactorCircuitLowerBeamDL_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gReactorCircuitLowerBeamDL_f3dlite_material_056_layerOpaque[];
extern Gfx gReactorCircuitLowerBeamDL[];
