extern u64 gPlantFragmentLeafDL_Forest_Small06_ci8[];
extern u64 gPlantFragmentLeafDL_Forest_Small06_pal_rgba16[];
extern Vtx gPlantFragmentLeafDL_gPlantFragmentLeafDL_mesh_layer_Transparent_vtx_cull[8];
extern Vtx gPlantFragmentLeafDL_gPlantFragmentLeafDL_mesh_layer_Transparent_vtx_0[4];
extern Gfx gPlantFragmentLeafDL_gPlantFragmentLeafDL_mesh_layer_Transparent_tri_0[];
extern Gfx mat_gPlantFragmentLeafDL_f3dlite_material_107_layerTransparent[];
extern Gfx gPlantFragmentLeafDL[];
