extern u64 gLinkAdultSheathDL_Sheath_00_rgba16[];
extern Vtx gLinkAdultSheathDL_gLinkAdultSheathDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gLinkAdultSheathDL_gLinkAdultSheathDL_mesh_layer_Opaque_vtx_0[10];
extern Gfx gLinkAdultSheathDL_gLinkAdultSheathDL_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gLinkAdultSheathDL_f3dlite_material_138_layerOpaque[];
extern Gfx gLinkAdultSheathDL[];
