extern u64 gAirVentCrackedDL_Air_Vent_01_ci4[];
extern u64 gAirVentCrackedDL_Air_Vent_01_pal_rgba16[];
extern Vtx gAirVentCrackedDL_gAirVentCrackedDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gAirVentCrackedDL_gAirVentCrackedDL_mesh_layer_Opaque_vtx_0[4];
extern Gfx gAirVentCrackedDL_gAirVentCrackedDL_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gAirVentCrackedDL_f3dlite_material_171_layerOpaque[];
extern Gfx gAirVentCrackedDL[];
