extern u64 gGearShaftSideLongDL__00010041_ci4[];
extern u64 gGearShaftSideLongDL__00010041_pal_rgba16[];
extern Vtx gGearShaftSideLongDL_gGearShaftSideLongDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gGearShaftSideLongDL_gGearShaftSideLongDL_mesh_layer_Opaque_vtx_0[10];
extern Gfx gGearShaftSideLongDL_gGearShaftSideLongDL_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gGearShaftSideLongDL_f3dlite_material_073_layerOpaque[];
extern Gfx gGearShaftSideLongDL[];
