extern SurfaceType gMovingPlatformUngrabCol_polygonTypes[];
extern CollisionPoly gMovingPlatformUngrabCol_polygons[];
extern Vec3s gMovingPlatformUngrabCol_vertices[8];
extern CollisionHeader gMovingPlatformUngrabCol_collisionHeader;
